persistence:
  type: pvc
  enabled: false
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection
  extraPvcLabels: {}
  disableWarning: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.observers.svc.cluster.local
        access: proxy
        isDefault: true
        httpMethod: POST
