
server:
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    size: 10Gi
    storageClass: ebs-sc
  extraFlags:
    - "web.enable-remote-write-receiver"

alertmanager:
  ## If false, alertmanager will not be installed
  ##
  enabled: false