[package]
name = "traidano"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    ".", "base",
    "bots",
]

[dependencies]
apca = {version = "0.29.0"}
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
env_logger = "0.11.3"
tokio = {version = "1.13", default-features = false, features = ["net", "macros", "rt", "rt-multi-thread"] }
config = "0.14.0"
serde = {version = "1.0.203", features = ["derive"]}
serde_yaml = "0.9.33"
log = "0.4.22"