apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster 
  region: eu-central-1

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true  

nodeGroups:
  - name: std-node
    instanceType: t3.medium
    desiredCapacity: 2


addons:
- name: aws-ebs-csi-driver
  wellKnownPolicies:
    ebsCSIController: true
  
