receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: 127.0.0.1:9090
    auth:
      authenticator: admin/admin
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [ otlp]
      exporters: [ debug ]
    logs:
      receivers: [ otlp ]
      exporters: [ debug ]