name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      OTLP_ENDPOINT: http://localhost:4318
      BASE_URL: https://paper-api.alpaca.markets/v2
      STREAM_URL : https://paper-api.alpaca.markets/v2
      API_KEY : API_KEY
      SECRET_KEY : SECRETE

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
